---
version: '3'
interval: '1500ms'

vars:
  KARPENTER_PROVIDER_TAG: instance-kwok
  CORPORATE_DOCKER_REPO: docker.io/your-corporate-repo/

tasks:
  mocks:
    cmds:
      - go install go.uber.org/mock/mockgen@v0.6.0
      - $(go env GOPATH)/bin/mockgen -package=mocks -destination=pkg/mocks/interface_mock.go k8s.io/client-go/kubernetes Interface
      - $(go env GOPATH)/bin/mockgen -package=mocks -destination=pkg/mocks/discovery_mock.go k8s.io/client-go/discovery DiscoveryInterface
  test:
    cmds:
      - go test -v ./... -coverprofile cover.out
  build:
    cmds:
      - go build ./...
  publish:
    cmds:
      - export KO_DOCKER_REPO=$CORPORATE_DOCKER_REPO && ko build --tags $KARPENTER_PROVIDER_TAG --bare ./cmd/controller
