---
version: '3'
interval: '1500ms'

tasks:
  mocks:
    cmds:
      - go install go.uber.org/mock/mockgen@v0.6.0
      - $(go env GOPATH)/bin/mockgen -package=mocks -destination=pkg/mocks/interface_mock.go k8s.io/client-go/kubernetes Interface
      - $(go env GOPATH)/bin/mockgen -package=mocks -destination=pkg/mocks/discovery_mock.go k8s.io/client-go/discovery DiscoveryInterface