apiVersion: v2
name: karpenter-crd
description: A Helm chart for Karpenter Custom Resource Definitions (CRDs).
type: application
version: 0.1.0 # x-release-please-version
appVersion: v0.1.0 # x-release-please-version
keywords:
  - cluster
  - node
  - scheduler
  - autoscaling
  - lifecycle
home: https://karpenter.sh/
sources:
  - https://github.com/aws/karpenter/
